language: node_js
node_js:
  - "6.10.2"
before_install:
  - rvm install 2.2.5
install:
  - gem install jekyll
  - gem install percy-cli
  - bundle install
  - npm install
before_script:
  - npm run build
script:
  - node_modules/gulp/bin/gulp.js test
  - percy snapshot --widths "375,1280" _jekyll/_site/ --baseurl "/vanilla-brochure-theme"
notifications:
  irc:
    channels:
      - "chat.freenode.net#vanilla-framework"
    on_success: change
    on_failure: always
    on_success: change
  slack:
    rooms:
      - vanillaframework:wvRcrt4C6ODhvHxrUkTaKlD5#general
